version: config-server-v0.0.3
# 健康检查
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
# rabbitMQ 配置
spring:
  rabbitmq:
    host: 192.168.56.128
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: true # 开启配置自动刷新
      trace:
        enabled: true